### ISSUE TITLE
soroban-cli: replace lab xdr subcommand with embedding the stellar-xdr cli

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/soroban-tools#1018]
The soroban-cli has a `lab xdr` sub command that supports decoding XDR.

However, the stellar-xdr cli tool has more features and is likely to be developed further than the soroban-cli's xdr command.

We should embed the stellar-xdr cli inside the soroban-cli, so that the soroban-cli benefits from the stellar-xdr.

```[tasklist]
### Tasks
- [x] Export the CLI from the stellar-xdr lib. https://github.com/stellar/rs-stellar-xdr/pull/326
- [x] Export the CLI root command run fns from the stellar-xdr lib. https://github.com/stellar/rs-stellar-xdr/pull/337
- [x] Release stellar-xdr. https://github.com/stellar/rs-stellar-xdr/pull/338
- [x] Update patch of soroban-env. https://github.com/stellar/rs-soroban-env/pull/1305
- [x] Release patch of soroban-env. https://github.com/stellar/rs-soroban-env/pull/1304
- [x] Update patch of soroban-sdk. https://github.com/stellar/rs-soroban-sdk/pull/1190
- [x] Release patch of soroban-sdk. https://github.com/stellar/rs-soroban-sdk/pull/1191
- [ ] Import that exported CLI into the soroban-cli. https://github.com/stellar/soroban-tools/pull/1135
```

**Comment by stellarsaur** [comment]
Just to clarify, the scope of this issue is to essentially merge [stellar/rs-stellar-xdr](https://github.com/stellar/rs-stellar-xdr) into soroban-cli, right? Should we deprecate/remove the original repo in that case?

**Comment by leighmcculloch** [comment]
No, the scope of the issue to embed the tool.
