### ISSUE TITLE
[epic] migrate Soroban RPC to soroban-rpc Repository

### ISSUE THREAD

**Issue by stellarsaur** [stellar/soroban-tools#1171]
See #1115 for motivation behind separating Soroban RPC from Soroban CLI.

This issue tracks all work that needs to be done to completely separate Soroban RPC.

## Done
- [x] Create soroban-rpc repository ([#1824](https://github.com/stellar/terraform/pull/1824))
- [x] Migrate Soroban RPC codebase into `soroban-rpc` repository
- [x] Remove code from `soroban-rpc` that isn't related to Soroban RPC (see [soroban-rpc#5](https://github.com/stellar/soroban-rpc/pull/5/files#))
- [x] Update Jenkins release jobs (e.g. [soroban-rpc-docker-builder](https://buildmeister-v3.stellar-ops.com/job/Platform/job/soroban-rpc-docker-builder/)) to point to `soroban-rpc` repository (see [pipelines#685](https://github.com/stellar/pipelines/pull/685))
- [x] Update System Tests to point to new `soroban-rpc` repository (see [soroban-rpc#6](https://github.com/stellar/soroban-rpc/pull/6))
- [x] Update Quickstart to point to new `soroban-rpc` repository (see [quickstart#558](https://github.com/stellar/quickstart/pull/558))
- [x] Update release process for Soroban RPC (see [soroban-rpc#6](https://github.com/stellar/soroban-rpc/pull/6))
- [x] Move open Soroban RPC issues to `soroban-rpc` repository
- [x] Update all public (and internal) docs that reference RPC to point to the new repo (see [this PR](https://github.com/stellar/soroban-docs/pull/714))
- [x] Merge/close all outstanding PRs for Soroban RPC in `soroban-tools` and add changes to `soroban-rpc` (see [this PR](https://github.com/stellar/soroban-rpc/pull/57))
- [x] Add workflows to publish [soroban-rpc crate](https://crates.io/crates/soroban-rpc) (see [this PR](https://github.com/stellar/soroban-rpc/pull/59))
- [x] Remove Soroban RPC code from `soroban-tools` (see [this PR](https://github.com/stellar/soroban-tools/pull/1198))
- [x] Update release process for Soroban CLI (see [this PR](https://github.com/stellar/soroban-tools/pull/1201))

**Comment by leighmcculloch** [comment]
> [ ] Migrate Soroban RPC codebase into `soroban-rpc` repository

It should be possible to preserve the git history of soroban-rpc. There are a couple ways that can be done while preserving the git history.

1. Simply push the soroban-tools repo to the soroban-rpc repo, so you have the entire history as is, then start deleting files and moving them around. By far the simplest, and you'll keep all past history including sha's exactly which is nice.

2. Use more complex git commands to retain the history without any of the other components. There's an example of how to do that here: https://github.com/stellar-deprecated/bridge-compliance?tab=readme-ov-file#bridge-and-compliance. This would end upwith a nicer looking history probably, but with all the SHAs changed which is annoying.

I think (1) could be a good approach, but defer to you.

**Comment by stellarsaur** [comment]
Considering the main repo migration complete now. Any additional tasks like updating workflows can be tracked separately.
