### ISSUE TITLE
[epic] add support for AuthNext

### ISSUE THREAD

**Issue by tsachiherman** [stellar/soroban-tools#346]
# What ? 

This is the epic ticket for the AuthNext support changes for the platform team.

The following are the dependent issues:

### Completed
- [x] https://github.com/stellar/soroban-tools/issues/347 [**1** story points]
- [x] https://github.com/stellar/soroban-tools/issues/348 [**3** story points]
- [x] https://github.com/stellar/js-stellar-base/pull/572
- [x] https://github.com/stellar/go/issues/4757 [**3** story points]
- [x] https://github.com/stellar/go/pull/4760
- [x] https://github.com/stellar/soroban-tools/issues/349 [**5** story points]
- [x] https://github.com/stellar/soroban-tools/issues/350 [**5** story points]
- [x] https://github.com/stellar/soroban-tools/issues/351 [**3** story points]
 
### In Progress
- [x] https://github.com/stellar/system-test/issues/19 [**5** story points]

**Comment by mollykarcher** [comment]
I'm going to close this. The system-test change is technically still pending, but it is merged and just waiting for next release
