### ISSUE TITLE
soroban-rpc: Change the api to support multiple footprints for eventual multi-operations support

### ISSUE THREAD

**Issue by paulbellamy** [stellar/soroban-tools#363]
At this point in the API, we should support multiple footprints (one per operation). This won't be used *now*, but will mean we don't need to change the API (or all the clients) when we add multi-operation support.
https://github.com/stellar/soroban-tools/blob/ee9d1d132831c697cfd709646bc3da8212625bb4/cmd/soroban-rpc/internal/methods/simulate_transaction.go#L85

# TODO
- [ ] Add a new field in soroban-rpc (`footprints`?)
- [ ] deprecate the old one
- [ ] Update soroban-docs
- [ ] update the js client
- [ ] update the cli client
- [ ] release the deprecation
- [ ] remove the field in the next release
