### ISSUE TITLE
[epic] Remove horizon dependency for sendTransaction and getTransactionStatus endpoints

### ISSUE THREAD

**Issue by tamirms** [stellar/soroban-tools#409]
soroban-rpc currently uses horizon for submitting transactions and obtaining transaction results. Given that soroban-rpc is now running captive core, we should be able to come up with a new architecture where transaction submission in soroban-rpc does not depend on horizon.

This issue will be complete when: 

- [x] the design for soroban txsub without horizon is proposed and approved: #444 
- [x] the implementation of the design is merged: #445
- [x] remove horizon from soroban rpc requirements:
    - [x] quickstart: https://github.com/stellar/quickstart/issues/430
    - [x] system-test: https://github.com/stellar/system-test/issues/32
    - [x] helm: [sdf helm chart config](https://github.com/stellar/helm-charts/blob/main/charts/soroban-rpc/values.yaml)
- [x] update soroban-cli to reflect new API: #446
- [x] update soroban js client to reflect new API: https://github.com/stellar/js-soroban-client/issues/51
- [x] update docs to reflect new API: https://github.com/stellar/soroban-docs/issues/333

We should make sure the design and implementation also addresses these related issues:

- [x] https://github.com/stellar/go/issues/4642
- [x] https://github.com/stellar/soroban-tools/issues/372
- [x] https://github.com/stellar/soroban-tools/issues/339
- [x] https://github.com/stellar/soroban-tools/issues/413

**Comment by tomerweller** [comment]
(This is a comment about `getTransactionStatus`, not sure if this is the right place - happy to move it)  

I suggest that we: 
1. rename `getTransactionStatus` to `getTransaction` 
2. remove the `pending` option from `status`  
3. only serve transactions that have been ingested 

Reasoning: core doesn't provide any information about the task queue and making assumptions about it, like a transaction being pending, is dangerous. For the sake of simplicity I propose that soroban-rpc provides only "known for sure" information, which is information produced by ingestion.
