### ISSUE TITLE
[Epic] MVP: RPC Productionalization for Testnet

### ISSUE THREAD

**Issue by jcx120** [stellar/soroban-tools#919]
(subset of Productionalization [epic](https://github.com/stellar/soroban-tools/issues/483))
Goal is to provide our 7+ infra providers with a minimal viable RPC deployment for them to deploy to Testnet and prepare for Mainnet. 

**Standardize standalone deployment**
- [x] https://github.com/stellar/soroban-tools/issues/382
AC: as an operator, I have a well defined package and method for installing and deploying the Soroban RPC as a standalone service, with recommended default settings. 

**Runbook:**
- [x] https://github.com/stellar/soroban-tools/issues/512
AC: As an operator, I'd like clear instructions on how to install / deploy, run, scale, monitor my instance so that I can provide a reliable service for the Soroban ecosystem users. 

**Benchmarking: Run minimal 1 round of load testing to profile saturation point and hotspots**
- [x] https://github.com/stellar/soroban-tools/issues/505
AC: as a developer, I would like to understand and document how the RPC performs under sustained load terms of max RPS, concurrency,  identify hotspots and breaking points. (These will also serve as inputs to inform alerting thresholds that can give operators a margin of safety and issues to address separately). 
- [x] https://github.com/stellar/soroban-tools/issues/554 (P2 - can be deferred if no issues from load testing)
(In the event there are critical issues from load testing, we can proceed to this one)

**Understand and document a minimum scaling strategy: eg, "for every X requests/sec, add 1 more instance"**
- [x] https://github.com/stellar/soroban-tools/issues/506
AC: As an operator, I want to have a clear understanding of what a single instance can service in terms of concurrent requests and maximum requests per second on a sustained basis so that I can scale and manage my operating costs predictably. 

**Logging / Error reporting:**
- [x] https://github.com/stellar/soroban-tools/issues/500
~AC: As an operator, I have a clear way to understand where to find logs in a single place for diagnostic, alerting and monitoring purposes.~
Referenced ticket is different from the AC articulated here. We're confident calling this AC done, but will leave the referenced ticket open to track/capture it's original intent

```[tasklist]
### Tasks
```

**Comment by sreuland** [comment]
note - new docs have been added for deploying rpc using Helm Chart - https://soroban.stellar.org/docs/reference/rpc#deploy-your-own-rpc-instance

**Comment by stellarsaur** [comment]
Going to close this epic as all of the relevant issues are closed. We can always reopen if new items come up for productionalizing Testnet.
